### ISSUE TITLE
Automation triggered at every boot of HA

### ISSUE THREAD

**Issue by pilot1981** [bruxy70/Garbage-Collection#146]
**Describe the bug**
After upgraded to 2.22/2.23 release I have automation related to sensor.raccolta_indifferenziata was triggered every time I reboot HASSIO

**Configuration**
YAML or Config Flow (GUI):

```sensors:
  - name: raccolta_indifferenziato_mattino
    frequency: "weekly"
    collection_days:
    - mon
    move_country_holidays: IT
  - name: raccolta_organico_mattino
    frequency: "weekly"
    collection_days:
    - mon
    - thu
    move_country_holidays: IT

```

**Error log/debug information**
```
No error
```
To enable debug logging, add `custom_components.garbage_collection: debug` to your config under logger/logs.

**Screenshots**

**Version**
Integration version, Home Assistant version and configuration

0.109.7 with HACS

**Comment by bruxy70** [comment]
If you enable debug, in the log it should say something like
```
2020-05-16 13:29:11 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (test) Calling update
2020-05-16 13:29:11 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (test) Found next date: 22-May-2020, that is in 6 days
```
Does that show the correct date there?

**Comment by pilot1981** [comment]
this are my debug logs:

```
garbage_collection
Version: 2.23
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/bruxy70/Garbage-Collection/issues
-------------------------------------------------------------------

2020-05-16 17:17:10 INFO (MainThread) [custom_components.garbage_collection] 
-------------------------------------------------------------------
garbage_collection
Version: 2.23
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/bruxy70/Garbage-Collection/issues
-------------------------------------------------------------------

2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_indifferenziato_mattino) Country Holidays with parameters: country: IT, prov: None, state: None, observed: True
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_indifferenziato_mattino) Found these holidays: 
  2020-06-02: Festa della Repubblica
  2020-08-15: Assunzione della Vergine
  2020-11-01: Tutti i Santi
  2020-12-08: Immacolata Concezione
  2020-12-25: Natale
  2020-12-26: Santo Stefano
  2021-01-01: Capodanno
  2021-01-06: Epifania del Signore
  2021-04-04: Pasqua di Resurrezione
  2021-04-05: Lunedì dell'Angelo
  2021-04-25: Festa della Liberazione
  2021-05-01: Festa dei Lavoratori
  2021-06-02: Festa della Repubblica
  2021-08-15: Assunzione della Vergine
  2021-11-01: Tutti i Santi
  2021-12-08: Immacolata Concezione
  2021-12-25: Natale
  2021-12-26: Santo Stefano
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_organico_mattino) Country Holidays with parameters: country: IT, prov: None, state: None, observed: True
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_organico_mattino) Found these holidays: 
  2020-06-02: Festa della Repubblica
  2020-08-15: Assunzione della Vergine
  2020-11-01: Tutti i Santi
  2020-12-08: Immacolata Concezione
  2020-12-25: Natale
  2020-12-26: Santo Stefano
  2021-01-01: Capodanno
  2021-01-06: Epifania del Signore
  2021-04-04: Pasqua di Resurrezione
  2021-04-05: Lunedì dell'Angelo
  2021-04-25: Festa della Liberazione
  2021-05-01: Festa dei Lavoratori
  2021-06-02: Festa della Repubblica
  2021-08-15: Assunzione della Vergine
  2021-11-01: Tutti i Santi
  2021-12-08: Immacolata Concezione
  2021-12-25: Natale
  2021-12-26: Santo Stefano
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (garbage_collection) Calling update
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (garbage_collection) Found next date: 19-May-2020, that is in 3 days
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_indifferenziato_mattino) Calling update
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_indifferenziato_mattino) Found next date: 18-May-2020, that is in 2 days
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_organico_mattino) Calling update
2020-05-16 17:17:25 DEBUG (MainThread) [custom_components.garbage_collection.sensor] (raccolta_organico_mattino) Found next date: 18-May-2020, that is in 2 days
```

I attach also other configurations, I hope these could be useful.

in configuration.yaml:
```
input_datetime:
# garbage collection addon entry to manage datetime
  only_time_organico:
    name: time_organico
    has_date: false
    has_time: true
    initial: '19:45'
  only_time_indifferenziata:
    name: time_indifferenziata
    has_date: false
    has_time: true
    initial: '19:55'
  datetime_organico:
    name: datetime_organico
    has_date: true
    has_time: true
  datetime_indifferenziata:
    name: datetime_indifferenziata
    has_date: true
    has_time: true
```

my automation for sensor indifferenziata:

```
automation:
  alias: "Notifica ritiro indifferenziata"
  trigger:
    platform: numeric_state
    entity_id: sensor.raccolta_indifferenziata_mattino
    value_template: "{{ state.attributes.days }}"
    below: 1
  condition: []
  action:
# Sets date and time to date and time from timestamp (current date and time in this example)
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.datetime_indifferenziata
        date: >
          {{ now().timestamp() | timestamp_custom("%Y-%m-%d", true) }}
        time: >
          {{ now().timestamp() | timestamp_custom("%H:%M:%S", true) }}
```

and automation notification 20 hours after midnight:

```
automation:
- alias: "notifica il giorno dopo il ritiro indifferenziata"
  trigger:
    platform: template
    value_template: "{{ states('sensor.date_time').replace(',', '')|as_timestamp >= state_attr('input_datetime.datetime_indifferenziata', 'timestamp') + 20*60*60 }}"
  condition: []
  action:
    - service: notify.famiglia
      data:
        message: "Attenzione: oggi è giorno di ritiro indifferenziata."
    - service: notify.alexa_media
      data:
        target: 
          - media_player.echo_dot_di_daniele
        data:
          type: announce
        message: "Attenzione: oggi è giorno di ritiro indifferenziata."
```

the other automation of organic isn't triggered after HASSIO reboot...
