### ISSUE TITLE
Documentation on Notification Automation

### ISSUE THREAD

**Issue by rosscullen** [bruxy70/Garbage-Collection#149]
**Is your feature request related to a problem? Please describe.**
Would be great to see an example for an automation to send you notification message the night before bins go out. Some garbage/bin services send you SMS reminders (mine doesn't) but would be great to have it via Home Assistant and your excellent plugin.

**Describe alternatives you've considered**
I had a stab at creating one but it doesn't appear to be triggering:

```
- id: '1559395683959'
  alias: Notification to put bins out
  description: ''
  trigger:
  - entity_id: sensor.bins_collection
    from: '2'
    platform: state
    to: '1'
  condition: []
  action:
  - data:
      message: Don't forget to put out bins
      title: Bin Notification
    service: notify.mobile_app_smartphone
```

**Additional context**
Appreciate to see a few example notifications. Thanks as always
