### ISSUE TITLE
howto hide garbage_collection item in calendar

### ISSUE THREAD

**Issue by pilot1981** [bruxy70/Garbage-Collection#168]
Hi,
I don't understand howto hide garbage_collection item in my calendar:
<img width="970" alt="Schermata 2020-06-09 alle 15 56 45" src="https://user-images.githubusercontent.com/46350465/84156741-2dcebc00-aa6a-11ea-80be-0494797ddf8f.png">
example: howto hide item in 9 june?

You can explain me howto do it?

regards

**Comment by bruxy70** [comment]
You can 'hide' the whole entity from the calendar by setting the parameter `hidden`. That will hide the whole sensor so that the calendar will not show it. But it will still be there.
But I think what you are referring to is skipping a collection date. So the next collection will not be 9th, but 16th. In that case, just add that date to `exclude_dates`. Or if you want to skip all public holidays, there is that feature too.

**Comment by pilot1981** [comment]
please, can you explain where I have to use parameter hidden?

thanks

**Comment by bruxy70** [comment]
![image](https://user-images.githubusercontent.com/44951610/84158551-4a6bf380-aa6c-11ea-933b-56e66fd5a24a.png)

or if you configure it in yaml:
```yaml
garbage_collection:
  sensors:
  - name: "Tuesday collection"
    hidden: True
    frequency: "weekly"
    collection_days: "tue"
```
