### ISSUE TITLE
Adjustable Holiday offset

### ISSUE THREAD

**Issue by grahamr** [bruxy70/Garbage-Collection#184]
Currently the holiday schedule defers collection to the following date. I would like to be able to offset that by a certain number of days (before or after), similar to the workaround to get the "last Saturday of the month" type -7 offset.

Our garbage collection schedule here uses Saturday as the alternative collection date, so if your collection falls on Monday, the previous Saturday is the date it would be picked up, but if you fall on a Friday, the following Saturday would be the collection date.

I would like to provide a variable (in my case -2, as my collection is Monday) to the Holiday Collection offset so that the calendar bumps back 2 days if there is a holiday on a Monday.

Currently I am working on building a manual list of include and exclude dates, but as I have 3 different types of collection (recycling, organic, garbage) on alternating varied weeks it makes it a bit tricky to figure out which one is on which holiday.

**Comment by bruxy70** [comment]
Added to 3.03-beta. Please test it ane let me know. Thanks.

**Comment by grahamr** [comment]
I pulled the new files, popped in the new values for config, and suspect I missed something minor

```
garbage_collection:
  sensors:
  - name: Waste # Every second week on Monday
    frequency: "even-weeks"
    collection_days: "mon"
    verbose_state: True
    verbose_format: "on {date}\n(in {days} days)"
    move_country_holidays: CA
    prov: NS
    holiday_move_offset: -2
```

`Invalid config for [garbage_collection]: value must be at least 1 for dictionary value @ data['garbage_collection']['sensors'][0]['holiday_move_offset']. Got -2. (See /config/configuration.yaml, line 140). Please check the docs at https://github.com/bruxy70/Garbage-Collection/`
