### ISSUE TITLE
no entities generate

### ISSUE THREAD

**Issue by chpiero** [bruxy70/Garbage-Collection#186]
I installed garbage_collection as per guide but when I restart HASSIO I can't find the entities. In my configuration I have a separate sensors.yaml file not in the configuration ... I had to change the syntax a bit but it didn't give me an error.

here below the yaml code inside sensors.yaml

```
  - platform: garbage_collection
    name: "indifferenziato"
    frequency: "weekly"
    verbose_state: true
    collection_days:
      - mon
      - fri
```

my Home Assistant version is 0.114.1
