### ISSUE TITLE
Changes in planning don't take immediate effect

### ISSUE THREAD

**Issue by TheGroundZero** [bruxy70/Garbage-Collection#189]
**Describe the bug**

My initial setup included a weekly repeating schedule.
I later changed this to match the actual garbage collection schedule.
Changes are reflected in the *Calendar* but not in the sensor state or the Lovelace UI (via card-templater).

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : YAML

```yaml
garbage_collection:
  sensors:
    - name: "Restafval"
      frequency: weekly
      collection_days:
      - tue
      expire_after: '12:00'
      move_country_holidays: 'BE'
    - name: "PMD"
      frequency: odd-weeks
      collection_days:
      - tue
      expire_after: '12:00'
      move_country_holidays: 'BE'
    - name: "Papier/karton"
      frequency: every-n-weeks
      collection_days:
      - tue
      period: 4
      first_week: 2
      expire_after: '12:00'
      move_country_holidays: 'BE'
```

**Error log/debug information**

```txt
n/a
```

**Screenshots**

![image](https://user-images.githubusercontent.com/2406013/91081311-742dc300-e636-11ea-9a70-f3823fea20cc.png)
![image](https://user-images.githubusercontent.com/2406013/91081329-7b54d100-e636-11ea-99c7-ff0a3ecc320e.png)

sensor.papier_karton
```yaml
state: 1
next_date: '2020-08-25T00:00:00+02:00'
days: 1
last_collection: null
last_updated: '2020-08-24T00:00:01.789138+02:00'
friendly_name: Papier/karton
icon: 'mdi:trash-can'
device_class: garbage_collection__schedule
```

**Version**

Integration version: 3.04

Home Assistant version: HassOS 4.12

**Comment by bruxy70** [comment]
And this is after HA restart?
I have tried the same configuration on my HA (using Config-flow, so I did not have to restart), and it seems to show correctly Sep 15.
![image](https://user-images.githubusercontent.com/44951610/91085954-7d2a8e80-e64e-11ea-91e5-3b7943d56495.png)

**Comment by TheGroundZero** [comment]
I rebooted HA to get the updates in the calendar, but the view didn't update.
It did change after midnight.

I am using YAML instead of config flow. Perhaps there's a different trigger there?

```yaml
next_date: '2020-08-25T00:00:00+02:00'
days: 0
last_collection: null
last_updated: '2020-08-25T00:00:23.990323+02:00'
friendly_name: Restafval
icon: 'mdi:delete-restore'
device_class: garbage_collection__schedule
```
