### ISSUE TITLE
Service to triggering temporary slide

### ISSUE THREAD

**Issue by stboch** [bruxy70/Garbage-Collection#190]
**Is your feature request related to a problem? Please describe.**

In my area there are events (inclimate weather) beyond standard holidays that will cause the collections to slide one day.

**Describe the solution you'd like**

a service call much like collect_garbage to slide the collections 1 or more days

**Describe alternatives you've considered**

Adding new holidays to trigger a slide but a bit hacky...

**Additional context**

```
slide_collection:
  description: Slide the next collection.
  fields:
    entity_id:
      description: The garbage_collection sensor entity_id
      example: sensor.general_waste
    days:
      description: Slide Collection by X days
      example: 2
```
