### ISSUE TITLE
Custom element doesn't exist: card-templater.

### ISSUE THREAD

**Issue by ojdas** [bruxy70/Garbage-Collection#191]
Hi,

I have instaled your integration along with Lovelace Card Templater but I receive this error message
![error](https://user-images.githubusercontent.com/5883257/91581241-7e113800-e94e-11ea-993a-42eb730bfd24.png)
Where is the problem? During integration o rather code?
I'm using your example:

```
      - type: 'custom:card-templater'
        card:
          type: picture-entity
          name_template: >-
            {{ states.sensor.bio.attributes.days }} days
          show_name: True
          show_state: False
          entity: sensor.general_waste
          state_image:
            "0": "/local/containers/general_today.png"
            "1": "/local/containers/general_tomorrow.png"
            "2": "/local/containers/general_off.png"
        entities:
          - sensor.general_waste
```

As well whether below parts of code should be also added to HA configuration file?

```
garbage_collection:
  sensors:
  - name: "General Waste"
    frequency: "odd-weeks"
    first_month: "oct"
    collection_days: thu
```
