### ISSUE TITLE
Every-n-weeks collection has problem on the end and start of the year.

### ISSUE THREAD

**Issue by oiv** [bruxy70/Garbage-Collection#218]
**Describe the bug**

I have two collections. One starting from week 2 (2020) every 4 weeks. Other starting from week 6 for every 8 weeks. This works ok for 2020, but now when the year is changing the weeks do not match. I need to wait until the end of the yeat and readjust the starting week to week 1 to follow the 4 week pattern.

I think the start week should have a date instead of a week number so it stays constant even when the year changes.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? :  Config Flow

```yaml
            {
                "entry_id": "1da5c27441e2473d9f17e016badc5c66",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Energiaj\u00e4te",
                "data": {
                    "unique_id": "d8d20ce9-b53f-40ca-ac96-dca0d7fabaa9",
                    "frequency": "every-n-weeks",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_state": true,
                    "verbose_format": "Tyhjennys {date}, {days} p\u00e4iv\u00e4n p\u00e4\u00e4st\u00e4",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "wed"
                    ],
                    "first_month": "jan",
                    "last_month": "dec",
                    "period": 4,
                    "first_week": 2,
                    "holiday_move_offset": 1,
                    "observed": true,
                    "holiday_in_week_move": false
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            },
            {
                "entry_id": "42a1bfb345724ad38702562b7b67eb5e",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Kaatopaikkaj\u00e4te",
                "data": {
                    "unique_id": "28efc028-3962-4db6-ab3a-c1718769e5c0",
                    "frequency": "every-n-weeks",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_state": true,
                    "verbose_format": "Tyhjennys {date}, {days} p\u00e4iv\u00e4n p\u00e4\u00e4st\u00e4",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "wed"
                    ],
                    "first_month": "jan",
                    "last_month": "dec",
                    "period": 8,
                    "first_week": 6,
                    "holiday_move_offset": 1,
                    "observed": true,
                    "holiday_in_week_move": false
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            },

```

**Error log/debug information**

```txt

```

**Screenshots**

![image](https://user-images.githubusercontent.com/226812/102787170-4fa9e380-43a9-11eb-8726-5375754b4e35.png)

**Version**

Integration version: 3.10

Home Assistant version:  2020.12.1
