### ISSUE TITLE
Next Week not correct

### ISSUE THREAD

**Issue by luckyzor** [bruxy70/Garbage-Collection#226]
**Describe the bug**
 First week of the month it's not correct, there are 2 weeks in a row.  it should be 28 December and 11 January // not 28 December and again 4 January (please check screen shot)

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

```yaml
garbage_collection:
  sensors:
    - name: "Household waste"
      frequency: "weekly"
      verbose_state: true
      verbose_format: "{date}, in {days} days"
      date_format: "%d/%m"
      collection_days:
        - mon
      move_country_holidays: BE
      holiday_in_week_move: true
      # exclude_dates:
      # - '2019-04-13'
      # - '2019-06-01'
      # include_dates:
      # - '2019-04-14'
      # - '2019-06-02'
    - name: "Recyclable waste"
      frequency: "odd-weeks"
      verbose_state: true
      verbose_format: "{date}, in {days} days"
      date_format: "%d/%m"
      collection_days:
        - mon
      move_country_holidays: BE
      holiday_in_week_move: true
```

**Error log/debug information**

```txt
No error
```

**Screenshots**

![image](https://user-images.githubusercontent.com/31155573/103177850-6efbb180-487e-11eb-9e7e-508fd4cdbbc5.png)

**Version**

Integration version:  3.11

Home Assistant version: 2020.12.7
