### ISSUE TITLE
Config entry was never loaded

### ISSUE THREAD

**Issue by Neonox31** [bruxy70/Garbage-Collection#236]
Hello and happy new year,

First thanks for the hard work on this addon 👍
I'm new with HA and I have installed this addons using HACS without problem, all seems to work well but I got the following error in logs each time I restart HA :
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 8:15:46 (1 occurrences)
Last logged: 8:15:46

Error unloading entry configuration.yaml for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

Here is my configuration :
```yaml
garbage_collection:
  sensors:
    - name: 'Poubelle grise'
      frequency: 'weekly'
      collection_days: 'mon'
      expire_after: '08:00'
      move_country_holidays: FRA
    - name: 'Poubelle jaune'
      frequency: 'even-weeks'
      collection_days: 'fri'
      expire_after: '10:00'
      move_country_holidays: FRA
```

Any clue to prevent the error ? Maybe my configuration is wrong ?

Thanks for your help.

**Comment by bruxy70** [comment]
Hi. Please try FR as the country code for holidays. I share the validation list with the list of values for the GUI (config flow) configuration, and it would not make sense to show 3 different values for each country.
Also, I think it is easier to configure it in config flow - that should make sure the configuration is valid.

**Comment by Neonox31** [comment]
Thanks for your answer.

I tried `FR` as country yesterday but it results as the following error :
```
Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:122
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 9:36:21 (1 occurrences)
Last logged: 9:36:21

Invalid config for [garbage_collection]: value is not allowed for dictionary value @ data['garbage_collection']['sensors'][0]['move_country_holidays']. Got 'FR'. (See /config/configuration.yaml, line 19).
```

**Comment by bruxy70** [comment]
You are right, FRA is actually correct. Sorry for the confusion. I have tried your config and I do not get any error. How do you know it comes from this integration? 
It does not look like a configuration error, otherwise, it would not create the entity. And if you'd check the config, it would show the error as well. And it works. 
It is a pity the error does not say what entity this is about.

**Comment by Neonox31** [comment]
> You are right, FRA is actually correct. Sorry for the confusion. I have tried your config and I do not get any error. How do you know it comes from this integration?

No problem. I presume it came from `garbage_collection` config because when I comment the block the error disappears.
I'm totally new on HA and I probably made a mistake somewhere, I will investigate.
I found a similar issue here : https://community.home-assistant.io/t/garbage-collection-sensor-not-created/212830 but I don't understand the solution.

**Comment by Neonox31** [comment]
I could catch these lines with debug level :
```
2021-01-06 09:05:15 DEBUG (MainThread) [homeassistant.components.upnp] async_setup, config: OrderedDict([('default_config', {}), ('tts', [OrderedDict([('platform', 'google_translate'), ('language', 'fr')])]), ('vacuum', [OrderedDict([('platform', 'xiaomi_vacuum'), ('host', 'xxxx'), ('token', 'xxxx'), ('name', 'Henri')])]), ('garbage_collection', OrderedDict([('sensors', [OrderedDict([('name', 'Poubelle grise'), ('frequency', 'weekly'), ('collection_days', 'mon'), ('expire_after', '08:00'), ('move_country_holidays', 'FRA')]), OrderedDict([('name', 'Poubelle jaune'), ('frequency', 'even-weeks'), ('collection_days', 'fri'), ('expire_after', '10:00'), ('move_country_holidays', 'FRA')])])])), ('logger', OrderedDict([('default', 'debug')])), ('group', {})
```
Maybe the empty group here is related to https://community.home-assistant.io/t/garbage-collection-sensor-not-created/212830/5 ?

And the error with an extra line of sensor removal :
```
2021-01-06 09:05:14 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry configuration.yaml for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 321, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
return await hass.data[DOMAIN].async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-01-06 09:05:14 INFO (MainThread) [custom_components.garbage_collection] Successfully removed sensor from the garbage_collection integration
```

**Comment by bruxy70** [comment]
Ok. Not sure what the problem is. I did copy your configuration in my configuration, restarted and I get no such error.

**Comment by Neonox31** [comment]
Using the UI config via integrations section seems to be working and no error is thrown, is there a way to view the generated yaml config ?

**Comment by bruxy70** [comment]
Interesting. You can check the file /config/.storage/core.config_entries and search for garbage collection or your senior name. Not sure if this is the same format though.

**Comment by Neonox31** [comment]
OK thanks, here is the config_entries :
```json
{
                "entry_id": "75bc2b359da3be93b0c94293d9a9b425",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Poubelle grise",
                "data": {
                    "unique_id": "aee948e3-830e-4201-a627-750f2b4c7768",
                    "frequency": "weekly",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "expire_after": "08:00",
                    "collection_days": [
                        "mon"
                    ],
                    "first_month": "jan",
                    "last_month": "dec",
                    "holiday_move_offset": -1,
                    "observed": true,
                    "move_country_holidays": "FRA",
                    "holiday_in_week_move": false
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            },
            {
                "entry_id": "7dbcf75f9e717f5d79413e0142f1547d",
                "version": 1,
                "domain": "garbage_collection",
                "title": "Poubelle jaune",
                "data": {
                    "unique_id": "064d5b99-6447-43a4-bbd9-90c23d7df8c8",
                    "frequency": "even-weeks",
                    "icon_normal": "mdi:trash-can",
                    "icon_today": "mdi:delete-restore",
                    "icon_tomorrow": "mdi:delete-circle",
                    "expire_after": "11:00",
                    "verbose_format": "on {date}, in {days} days",
                    "date_format": "%d-%b-%Y",
                    "collection_days": [
                        "fri"
                    ],
                    "first_month": "jan",
                    "last_month": "dec",
                    "holiday_move_offset": 1,
                    "observed": true,
                    "move_country_holidays": "FRA",
                    "holiday_in_week_move": false
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            }
```

**Comment by Laeborg** [comment]
I get the same error, but just with some pretty simple sensors:
`name: "Regular Waste"
frequency: "even-weeks"
collection_days:
  - tue
expire_after: '14:00'`

When I disable the garbage_collection integration the error disappears.

**Comment by bruxy70** [comment]
Can't replicate. The configuration above works fine.

**Comment by Laeborg** [comment]
I'm in doubt if it could be because I've separated my configuration into different files.
Package is loaded here: https://github.com/Laeborg/homeassistant-config/blob/main/packages/garbage_collection.yaml
And the entities is loaded here: https://github.com/Laeborg/homeassistant-config/tree/main/entities/garbage_collections

**Comment by bruxy70** [comment]
Don't know. I do not split my config that way. I have 
`packages: !include_dir_named packages` in my `config.yaml`. And different files in the packages directory, one with the garbage collection. Anyhow, try to simplify the config, you can then start moving it back to see where it was it breaks - where is the problem.

**Comment by Laeborg** [comment]
I've tried every configuration and indentation I can think, moving it to one file, but same result.
You can see what I have tried here: https://github.com/Laeborg/homeassistant-config/commits/main/packages/garbage_collection.yaml

I'm on the latest version of HassOS (core updated to 2021.2.1).

**Comment by bruxy70** [comment]
What is the error exactly? If it works without a problem, this should not be anything serious.

**Comment by Laeborg** [comment]
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 12:09:38 PM (1 occurrences)
Last logged: 12:09:38 PM
Error unloading entry configuration.yaml for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 325, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 72, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by Neonox31** [comment]
The error appears only when sensors are added through YAML configuration.

FYI H.A recommends using the U.I onfiguration now for integrations (https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/#the-future-of-yaml) but the YAML configuration is still the most convenient for me.

Indeed starting from the docker image `home-assistant/home-assistant:stable`, after adding integration and configuration via YAML I don't have the error in question. Maybe a side effect of an other integration, I need to go deeper.

**Comment by fi-sch** [comment]
I discovered similar error on my instance. I'm not using UI for integration configuration, just YAML. More info here: https://github.com/home-assistant/core/issues/49261

Here's my config:
```
garbage_collection:
  sensors:
  - name: "Zmieszane"
    hidden: true
    frequency: "weekly"
    collection_days:
    - tue
    - fri
    icon_normal: mdi:delete-variant
    icon_today: mdi:delete-variant
    icon_tomorrow: mdi:delete-variant
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
    
  - name: "Tworzywa"
    hidden: true
    frequency: "weekly"
    collection_days:
    - thu
    icon_normal: mdi:recycle
    icon_today: mdi:recycle
    icon_tomorrow: mdi:recycle
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
    
  - name: "Papier"
    hidden: true
    frequency: "weekly"
    collection_days:
    - thu
    icon_normal: mdi:file
    icon_today: mdi:file
    icon_tomorrow: mdi:file
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
    
  - name: "Bio"
    hidden: true
    frequency: "weekly"
    collection_days:
    - tue
    icon_normal: mdi:bio
    icon_today: mdi:bio
    icon_tomorrow: mdi:bio
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
    
  - name: "Szkło"
    hidden: true
    frequency: "every-n-weeks"
    collection_days:
    - wed
    period: 2
    first_week: 1
    first_month: "mar"
    icon_normal: mdi:bottle-wine
    icon_today: mdi:bottle-wine
    icon_tomorrow: mdi:bottle-wine
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
    
  - name: "Zielone"
    hidden: true
    frequency: "weekly"
    collection_days:
    - tue
    first_month: "mar"
    last_month: "nov"
    icon_normal: mdi:leaf
    icon_today: mdi:leaf
    icon_tomorrow: mdi:leaf
    move_country_holidays: PL
    verbose_state: true
    verbose_format: 'za {days} dni'
```

Unfortunately, I can't migrate to UI config as there's no setting for 'collection_days' parameter.
