### ISSUE TITLE
Feature request: two schedules for one sensor

### ISSUE THREAD

**Issue by mdallaire** [bruxy70/Garbage-Collection#24]
Where I live we have a different schedule in the summer vs the winter for compost pickup. In the winter they pick it up once a month and in the summer they pick it up each week. Right now I have to setup to different schedules for the same bin. It would be nice to have more than one schedule for the same sensor.

```
- platform: garbage_collection
  name: Compost Été
  frequency: "weekly"
  collection_days: "wed"
  first_month: "may"
  last_month: "oct"
- platform: garbage_collection
  name: Compost Hiver
  frequency: "monthly"
  collection_days: "wed"
  first_month: "nov"
  last_month: "apr"
```

**Comment by bruxy70** [comment]
I will put it on the list. I think the configuration would have to look something like
```
garbage_collection:
  sensors:
    name: Compost
    schedules:
    - frequency: weekly
      collection_days: wed
      first_month: may
      last_month: oct
    - frequency: monthly
      collection_days: wed
      first_month: nov
      last_month: apr
```
I have now added configuration through `config_flow` to allow people changing entity_ids. There I'll have to figure out how to easily add multiple schedules to one sensor - perhaps something like a device with more sensors - something I'll have to study.
