### ISSUE TITLE
not working on HA

### ISSUE THREAD

**Issue by pilot1981** [bruxy70/Garbage-Collection#240]
**Describe the bug**

I notice in the latest weeks, I don't receive notification about garbage collection; I see events in my calendar, but I think something is broken

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

GUI

![Schermata 2021-01-14 alle 09 15 29](https://user-images.githubusercontent.com/46350465/104563020-6f02fc00-5649-11eb-9e87-4e45b345ef2f.png)

**Error log/debug information**

![Schermata 2021-01-14 alle 09 44 23](https://user-images.githubusercontent.com/46350465/104565863-36fdb800-564d-11eb-847f-f8d3018682cf.png)

**Screenshots**

I use this automation to notify garbage days:

```
automation:
  alias: "Notifica ritiro organico"
  trigger:
    platform: numeric_state
    entity_id: sensor.raccolta_organico_mattino
    value_template: "{{ state.attributes.days }}"
    below: 1
  condition: []
  action:
# Sets date and time to date and time from timestamp (current date and time in this example)
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.datetime_organico
        date: >
          {{ now().timestamp() | timestamp_custom("%Y-%m-%d", true) }}
        time: >
          {{ now().timestamp() | timestamp_custom("%H:%M:%S", true) }}
```

```
automation:
- alias: "notifica il giorno dopo il ritiro organico"
  trigger:
    platform: template
    value_template: "{{ states('sensor.date_time').replace(',', '')|as_timestamp >= state_attr('input_datetime.datetime_organico', 'timestamp') + 20*60*60 }}"
#  condition: []
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_runtime_in_minutes
      above: 15
  action:
    - service: notify.famiglia
      data:
        message: "Attenzione: oggi è giorno di ritiro organico!"
    - service: notify.alexa_media
      data:
        target: 
          - media_player.echo_dot_di_daniele
        data:
          type: announce
        message: "Attenzione: oggi è giorno di ritiro organico!"
```

**Version**

Integration version: 

HACS 1.9.0

Home Assistant version: 

HASSIO 2021.1.1

**Comment by bruxy70** [comment]
Not sure why the automation does not kick in. Hard to debug from here. Is the entity state changing from 1 to 0 at the collection day? Is the automation triggered?

**Comment by pilot1981** [comment]
it seems there right value in sensor...

![Schermata 2021-01-14 alle 10 17 47](https://user-images.githubusercontent.com/46350465/104570334-12580f00-5652-11eb-98c0-f6928dbd0b05.png)

**Comment by bruxy70** [comment]
Ok. Then it should be an issue with the automation.

**Comment by pilot1981** [comment]
I understood problem is related to this part of automation:

```
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_runtime_in_minutes
      above: 15
```

thi is workaround you suggested me to avoid automation trigger every time I reboot HA...
