### ISSUE TITLE
Is there a maximum number of sensors? 

### ISSUE THREAD

**Issue by jp-dorion** [bruxy70/Garbage-Collection#255]
Hi, first of all thanks for this work, it's amazing.

I'd like to know if there's a maximum number of sensor's? I want to have 4 sensors, but there's only 3 showing up. 
The one who's named "Gros rebuts" is not showing up, even if I change the order in the YAML file, and I can't see why.

The first, second and fourth works very well.

 Here's my YAML file:
```
garbage_collection:
  sensors:
  - name: "Poubelles"
    icon_normal: "mdi:trash-can"
    icon_tomorrow: "mdi:trash-can"
    icon_today: "mdi:trash-can"
    frequency: "every-n-weeks"
    period: "2"
    first_week: "2"
    collection_days: "wed"
    verbose_state: true
    verbose_format: "dans {days} jours"
    expire_after: '12:00'
  - name: "Composte"
    icon_normal: "mdi:food-apple"
    icon_tomorrow: "mdi:food-apple"
    icon_today: "mdi:food-apple"
    frequency: "weekly"
    first_month: "apr"
    last_month: "nov"
    collection_days: "mon"
    verbose_state: true
    verbose_format: "dans {days} jours"
    expire_after: '12:00'
  - name: "Gros rebuts"
    icon_normal: "mdi:sofa-single"
    icon_tomorrow: "mdi:sofa-single"
    icon_today: "mdi:sofa-single"
    frequency: "monthly"
    first_week: "2"
    collection_days: "thu"
    verbose_state: true
    verbose_format: "dans {days} jours"
  - name: "Recyclage" 
    icon_normal: "mdi:recycle"
    icon_tomorrow: "mdi:recycle"
    icon_today: "mdi:recycle"
    frequency: "every-n-weeks"
    period: "2"
    collection_days: "wed"
    verbose_state: true
    verbose_format: "dans {days} jours"
    expire_after: '12:00'
```
Thank you
