### ISSUE TITLE
Next date not shown for group entity

### ISSUE THREAD

**Issue by andreapazzo** [bruxy70/Garbage-Collection#272]
**Describe the bug**

After create an entity group and added to card entities with other single entities, next date is not showed but is show the number of entities of group.

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 

```yaml
# Umido
- name: "Umido Inverno"
  hidden: true
  first_month: "sep"
  last_month: "may"
  frequency: "weekly"
  verbose_state: true
  verbose_format: '{date} ({days} giorni)'
  date_format: '%d/%m/%Y'
  collection_days:
  - wed
  - sat
- name: "Umido Estate"
  hidden: true
  first_month: "jun"
  last_month: "aug"
  frequency: "weekly"
  verbose_state: true
  verbose_format: '{date} ({days} giorni)'
  date_format: '%d/%m/%Y'
  collection_days:
  - mon
  - wed
  - sat
- name: "Umido"
  frequency: "group"
  entities:
    - sensor.umido_inverno
    - sensor.umido_estate
```

**Error log/debug information**

```txt

```

**Screenshots**

![immagine](https://user-images.githubusercontent.com/71377753/120099861-15095b80-c13e-11eb-9428-82a5b08efbd6.png)

**Version**

Integration version: 3.1.8

Home Assistant version: core-2021.4.6
