### ISSUE TITLE
Sensor state not kicking off automation

### ISSUE THREAD

**Issue by gavinpbennett** [bruxy70/Garbage-Collection#277]
I am a bit of a HA noob, but have managed to work my way around most things so far. I am trying to setup a text to speech automation, that triggers based on the state (1) of a sensor that I have setup with this integration. TTS is working as I have this action working for other automations. Please could someone tell me why this TTS is not working, at 7pm, the day before this scheduled event?

```
alias: TTS reminder - Cleaner coming tomorrow
description: ''
trigger:
  - platform: state
    entity_id: sensor.cleaner
    to: '1'
    for: '19:00:00'
condition: []
action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.sonos_lounge
      message: >-
        This is a friendly reminder that the cleaner is coming tomorrow, don't
        forget to put the money on the bench.
      cache: true
      language: en
mode: single
```
