### ISSUE TITLE
2021.12.b0 device_state_attributes warnings

### ISSUE THREAD

**Issue by tomlut** [bruxy70/Garbage-Collection#299]
**Describe the bug**

The Home Assistant 2021.12.b0 beta version generates the following warnings:
```
2021-12-04 13:05:45 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.waste (<class 'custom_components.garbage_collection.sensor.GarbageCollection'>) implements device_state_attributes. Please report it to the custom component author.
2021-12-04 13:05:45 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.recycling (<class 'custom_components.garbage_collection.sensor.GarbageCollection'>) implements device_state_attributes. Please report it to the custom component author.
```

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : 
YAML

```yaml
garbage_collection:
  sensors:
  - name: "Waste" # Each week on Monday
    frequency: "weekly"
    collection_days: "mon"
    hidden: true
  - name: "Recycling" # Bi-weekly on Monday
    frequency: "every-n-days"
    period: 14
    first_date: '2020-07-13'
    hidden: true
```

**Error log/debug information**

```txt

```

**Screenshots**

**Version**

Integration version: 3.2.0

Home Assistant version: 2021.12.b0
