### ISSUE TITLE
Monthly schedule

### ISSUE THREAD

**Issue by petersem** [bruxy70/Garbage-Collection#305]
Hi, I'm trying to configure a sensor to report on monthly payments (on 16th), however i haven't quite got it right. Can you advise?

Here is what i have:
```
garbage_collection:
  sensors:
    - name: "Car Insurance Payment 88"
      frequency: monthly
      period: 16
      icon_normal: mdi:car
      icon_tomorrow: mdi:shield-car
      verbose_state: True
      verbose_format: "in {days} days"
```
