### ISSUE TITLE
2 new issues

### ISSUE THREAD

**Issue by danielbrunt57** [bruxy70/Garbage-Collection#309]
**Describe the bug**

1. My recycle sensor has removed the most recent holiday from the list which was New Year's Day (Observed) Monday January 3rd 2022,  As a result of this, it has determined that today is recycling day but in fact it should be tomorrow. (Edit Jan 7/22: This was an error in [python-holidays](https://github.com/dr-prodigy/python-holidays) which incorrectly determined that Fri Dec 31 2021 was the Observed Holiday)
2. The last collection date is wrong.  It says 2020-12-31 but should say 2021-12-31

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : Config Flow

sensor.recycling:
```
next_date: '2022-01-06T00:00:00-08:00'
days: 0
last_collection: '2020-12-31T10:26:16.714169-08:00'
last_updated: '2022-01-06T07:20:04.422063-08:00'
holidays: |2-

    2022-02-21: Family Day
    2022-04-15: Good Friday
    2022-04-18: Easter Monday
    2022-05-23: Victoria Day
    2022-07-01: Canada Day
    2022-08-01: British Columbia Day
    2022-09-05: Labour Day
    2022-10-10: Thanksgiving
    2022-11-11: Remembrance Day
    2022-12-25: Christmas Day
    2022-12-26: Christmas Day (Observed)
    2023-01-01: New Year's Day
    2023-01-02: New Year's Day (Observed)
device_class: garbage_collection__schedule
icon: mdi:delete-restore
friendly_name: Recycling
```

**Error log/debug information**

```
No errors logged
```

**Screenshots**

**Version**

Integration version: 2021.12

Home Assistant version: core-2021.12.8

**Comment by bruxy70** [comment]
Ok, got it. The whole thing is designed to look forward, so when they added the holiday in a week, it would not see the holiday in the past. I will see if there is another way to deal with this feature that as part of the new version testing.

**Comment by danielbrunt57** [comment]
Thanks!

**Comment by bruxy70** [comment]
BTW, an example that adds an extra collection date a day after the calculated one
I think I will make a script to check for the holiday in week, make it a blueprint, and move this functionality to this automation

```yaml
alias: test garbage_collection event
description: >-
  Loop through all calculated dates, add extra collection a day after the calculate one
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: sensor.test
condition: []
action:
  - repeat:
      count: '{{ trigger.event.data.collection_dates | count }}'
      sequence:
        - service: garbage_collection.add_date
          data:
            entity_id: sensor.test
            date: >-
              {{ (as_datetime(trigger.event.data.collection_dates[repeat.index])
              + timedelta( days = 1)) | as_timestamp |
              timestamp_custom("%Y-%m-%d") }}
  - service: garbage_collection.update_state
    data:
      entity_id: sensor.test
mode: single
```
