### ISSUE TITLE
garbage_collection.remove_date: Could not parse date for dictionary value @ data['date']. Got None

### ISSUE THREAD

**Issue by danielbrunt57** [bruxy70/Garbage-Collection#310]
**Describe the bug**

Developer Tools > Services > Could not parse date for dictionary value

**Configuration**

Do you configure the integration in YAML or Config Flow (GUI)? : Config Flow

```
service: garbage_collection.remove_date
data:
  entity_id: sensor.recycling
  date: 2021-01-06T08:00:00.000Z
```

**Error log/debug information**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:44:06 AM (8 occurrences)
Last logged: 7:49:39 AM

[281472532588528] Error handling message: Could not parse date for dictionary value @ data['date']. Got None
```

**Screenshots**

**Version**

Integration version: v3.21 2021.12

Home Assistant version: core-2021.12.8
