### ISSUE TITLE
New verbose format

### ISSUE THREAD

**Issue by grm** [bruxy70/Garbage-Collection#33]
Hello,

I currently have this in my configuration :

```
garbage_collection:
  sensors:
  - name: Menager
    frequency: "weekly"
    verbose_state: True
    verbose_format: "Dans {days} jours"
    collection_days:
    - tue
    - fri
  - name: Recyclable
    frequency: "weekly"
    verbose_state: True
    verbose_format: "Dans {days} jours"
    collection_days:
    - wed
```

But in the UI, I still have the workd in english, as shown here (using lovelace) :
<img width="393" alt="Screenshot 2019-11-03 at 16 49 56" src="https://user-images.githubusercontent.com/70435/68087885-07a0c800-fe5a-11e9-9437-f58429030995.png">
 
Am I missing something ?

Thx,
Grm
