### ISSUE TITLE
Set date from sensor?

### ISSUE THREAD

**Issue by Naesstrom** [bruxy70/Garbage-Collection#389]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I've managed to get a [json source](https://edpfuture.ssam.se/FutureWeb/SimpleWastePickup/GetWastePickupSchedule?address=Billa+Katrinelund+1,+%C3%85ryd+(28683)) from my garbage collection company and made a date sensor for each bin from that via REST.
![image](https://user-images.githubusercontent.com/6575206/163688118-0b956cf1-c92d-4b7b-b3a3-10be51d2967b.png)
Karl_1_2 and Karl_2_2 is the ones with the date from the rest sensor and the others is from your component. Can I somehow use the rest sensors to set the date for the component, right now I'm just using the every-n-weeks approach.

**Comment by bruxy70** [comment]
Yes, you can use the manual update, and set the date by an automation triggered by the garbage collection loaded event. Check the documentation, and the included blueprints

**Comment by Naesstrom** [comment]
Ah yes I see, didn't dare to click the _"BEWARE, more advanced yaml here"_ part at first but it worked just great!
For future reference if someone else want's to do the same this is my automation
```yaml
alias: garbage_collection update bin1
description: 'Update collection date for bin 1 from rest sensor'
trigger:
  - platform: event
    event_type: garbage_collection_loaded
    event_data:
      entity_id: sensor.bin_1
action:
  - service: garbage_collection.add_date
    data:
      entity_id: '{{ trigger.event.data.entity_id }}'
      date: '{{ states("sensor.bin_1_rest") }}'
  - service: garbage_collection.update_state
    data:
      entity_id: sensor.bin_1
mode: single
```
Didn't work at first but that was just me being stupid, need to change the bins config to manual ^^ yes... like the manual says....
