### ISSUE TITLE
Add UI sample code?

### ISSUE THREAD

**Issue by 1DontEx1st** [bruxy70/Garbage-Collection#4]
I'm still new to HA, and fighting to try to get the neat view of my upcoming trash pickup that you show in sensor.png. Can you add sample UI/lovelace code to your repository? Thanks for the great component!

**Comment by bruxy70** [comment]
In my actual config, I use standard picture entity with state images:
```
 - type: picture-entity
   name: Bio
   show_name: True
   show_state: False
   entity: sensor.bio
   state_image:
     "0": "/local/bio_today.png"
     "1": "/local/bio_tomorrow.png"
     "2": "/local/bio_off.png"

```
In the readme, I used standard sensor entity - but that would just show 0,1,2 as the state. So I also added the lovelace-card-templater plugin (which requires card-tools), that allows formatting the displayed sensor state - both downloaded through HACS.

So the lovelace config looks like this:
On top, there are the two custom cards added:
```
resources:
  - type: js
    url: /community_plugin/lovelace-card-tools/card-tools.js
  - type: js
    url: /community_plugin/lovelace-card-templater/lovelace-card-templater.js
```
Then the entities:
```
  type: 'custom:card-templater'
  card:
    type: horizontal-stack
    cards:
      - entity: sensor.waste
        name: Waste
        type: sensor
  entities:
    - entity: sensor.waste
      state_template: >-
        {{ state_attr("sensor.waste","next_date") | as_timestamp |  timestamp_custom("%d-%b")  }} ({{ state_attr("sensor.waste","days") }} days)

```      
(Or I could have also created a template sensor)
