### ISSUE TITLE
How to use calendar trigger for collection reminder? Is this a HA bug?

### ISSUE THREAD

**Issue by alexeiw123** [bruxy70/Garbage-Collection#407]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I have a notification for bin day that I'd like to trigger form the calendar notification.
With testing I have been unable to achieve this, my test triggers are below, these were built using the UI.
I suspect I've stumbled across a big with either the trigger, the offset or how it handles all day calendar events. I thought I'd start here in case it's specific to this integration.

```
trigger:
  - platform: calendar
    event: start
    offset: '-6:0:0'
    entity_id: calendar.garbage_collection
  - platform: calendar
    event: start
    offset: '0:0:0'
    entity_id: calendar.garbage_collection
```

I am able to to successfully trigger a notification using a template trigger, but this presents it's own issues for repeat notifications when HA reboots.
```
trigger:
  - platform: template
    value_template: |
      {% if state_attr('calendar.garbage_collection','start_time') != none %}
        {% set start = state_attr('calendar.garbage_collection','start_time')|as_datetime|as_local %}
        {{ start - now() < timedelta(hours=12) }}
      {% endif %}
```
