### ISSUE TITLE
Feature Request: A state for next bin to be collected

### ISSUE THREAD

**Issue by CaptInsano** [bruxy70/Garbage-Collection#425]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Is your feature request related to a problem? Please describe.

I would like to set a conditional card to only show the next bin to be collected.

The current states in this addon allow me to show the the card when it is within a day of being collected but I would love more notice than that:

eg:
```
type: conditional
conditions:
  - entity: sensor.waste_bin
    state_not: '2'
card: 
  type: custom:garbage-collection-card
  entity: sensor.waste_bin

```

```
State
The state can be one of

Value	Meaning
0	Collection is today
1	Collection is tomorrow
2	Collection is later
```

### Describe the solution you'd like

Would it be possible to create a new state "3" meaning this is the next bin to be collected?

Eg:

```
State
The state can be one of

Value	Meaning
0	Collection is today
1	Collection is tomorrow
2	Collection is later
3      Next bin to be collected

```

It would make this a much easier thing to accomplish!

### Describe alternatives you've considered

I have tried to look at automations and helpers to set a helper toggle but I struggled 

### Additional context

Thanks so much for your work!
