### ISSUE TITLE
Can't remove Garbage_Collection entity

### ISSUE THREAD

**Issue by mothy-tim** [bruxy70/Garbage-Collection#447]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

Hi, I removed the integration and missed the entity! How do I remove it, please? It says I can't edit it as it has no ID! 
Thanks,
Tim

**Comment by bruxy70** [comment]
If you have removed the integration, then the integration cannot help you I am afraid. I think this is a general Home Assistant question.
Did you try re-installing it, removing the configured devices and uninstalling it again?
Or removing the entities from the list of entities.

**Comment by danielbrunt57** [comment]
I too removed the integration but had to go under the hood into HA files and manually remove the entity from /config/.storage/core.config_entries + stop HA & remove the entity from core.restore_state and then restart HA.
Fortunately, I have done this before so not a big deal.

I have replaced the integration with the HA (new) native calendar integration for my garbage collection which always occurs on Wednesday, no exceptions.  For recycling, I have used the HACS waste_collection_schedule integration as my Richmond site has ICS files available.  I created additional templated sensors so I can still use the lovelace custom:garbage-collection-card...

![image](https://user-images.githubusercontent.com/49846893/210127820-9aa3a269-c4e8-424c-9925-9c8cd9b2316b.png)
```
waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: Richmond Recycling
      args:
        url: https://recollect.a.ssl.fastly.net/api/places/8C86E114-C25F-11E2-ACE5-82EC225B0DBF/services/200/events.en.ics
      customize:
        - type: Recycling and green cart
          alias: Recycling Pickup
          icon: mdi:recycle
  day_switch_time: "11:00"
```
```
  - platform: waste_collection_schedule
    name: Recycling Collection Schedule
    details_format: appointment_types
    add_days_to: true
    types:
      - Recycling Pickup
    value_template: >
      {% if value.daysTo | int(0) > 2 %}
       2
      {% else %}
       value.daysTo
      {% endif %}
```
```
- sensor:
  - name: Recycling
    unique_id: recycling
    state: "{{ states('sensor.recycling_collection_schedule') }}"
    icon: mdi:recycle
    attributes:
      next_date: "{{ state_attr('sensor.recycling_collection_schedule', 'Recycling Pickup') }}"
      days: "{{ state_attr('sensor.recycling_collection_schedule','daysTo') }}"

  - name: Garbage
    unique_id: garbage_pickup
    state: >
      {% if state_attr("sensor.garbage","days") | int(0) > 2 %} 2
      {% else %} {{state_attr("sensor.garbage","days") }}
      {% endif %}
    icon: mdi:trash-can
    attributes:
      next_date: '{{ as_timestamp(state_attr("calendar.garbage_schedule", "start_time"))| timestamp_custom("%Y-%m-%d") }}'
      days: '{{ ((as_timestamp(state_attr("calendar.garbage_schedule","start_time")) - as_timestamp(now())) /60/1440)|round(0,"ceil")  }}'
```
Hope this helps someone!!
