### ISSUE TITLE
Migration off this integration since development is ending

### ISSUE THREAD

**Issue by genebean** [bruxy70/Garbage-Collection#462]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)

### Write your question here

I saw in the read me you are stopping work here since it’s not needed anymore… can you elaborate on how to replace this integration with the native bits?

**Comment by bruxy70** [comment]
Hi. I made a video about that on my channel. There might be some advanced functionalities that might still need some love, and I am looking forward to see the community to take it to the next level.

**Comment by genebean** [comment]
Awesome! Mind sharing a link to your channel?

**Comment by bruxy70** [comment]
https://www.youtube.com/@bruxy70

The custom card was made by someone else, I do not think it works with the local calendars, and no, you do not have to use the card like in my video.

**Comment by genebean** [comment]
Thanks! I looked at the card and it seems to rely mostly on the `next_date` attribute, so I took what you showed in your video and added that plus used some of what is on https://www.home-assistant.io/docs/configuration/templating/ to make for a way cleaner set of templates. The result is I have this in my config. I am still testing to verify it works as expected, but it sees like it will (today is trash day for me).

```yaml
- sensor:
    - name: "Days until trash pickup"
      state: "{{ min((as_local(as_datetime(state_attr('calendar.trash_can', 'start_time'))) - today_at('00:00')).days, 2) }}"
      unit_of_measurement: "D"
      icon: mdi:trash-can
      attributes:
        days: "{{ (as_local(as_datetime(state_attr('calendar.trash_can', 'start_time'))) - today_at('00:00')).days }}"
        next_date: "{{ as_local(as_datetime(state_attr('calendar.trash_can', 'start_time'))).isoformat() }}"

```
