### ISSUE TITLE
Command Line Sensor is moving

### ISSUE THREAD

**Issue by prolife86** [bruxy70/Garbage-Collection#466]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Garbage-Collection/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Garbage Collection, or the next pre-release.
- [x] I have enabled debug logging for my installation.

### Describe the bug

HA Is changing its Command Line sensors, see warning:

```
Command Line YAML configuration has moved
This stops working in version 2023.8.0. Please address before upgrading.
Configuring Command Line sensor using YAML has moved.

Consult the documentation to move your YAML configuration to integration key and restart Home Assistant to fix this issue.
```

Also see:
Should be something like:
https://community.home-assistant.io/t/configuring-command-line-sesor-using-yaml-has-moved-consult-the-documentation-to-move-your-yaml-configuration-to-integration-key-and-restart-home-assistant-to-fix-this-issue/579429/26

I solved it by:
-removing this from configuration.yaml:
```
# Oud Papier Sensor
  - platform: command_line
    name: Import Garbage Schedule
    unique_id: Oud_Papier_TXT
    command: "sh /share/import_dates.sh"
```
And at the top including (before "homeassistant:" etc.:
`command_line: !include command_line.yaml`

-creating command_line.yaml
entering:
```
- sensor:
     name: "Import Garbage Schedule"
     command: "sh /share/import_dates.sh"
     unique_id: Oud_Papier_TXT
```

Now the error message is gone and the command line integration seems to be working.

### Configuration
Old in configuration.yaml:
```
# Oud Papier Sensor
  - platform: command_line
    name: Import Garbage Schedule
    unique_id: Oud_Papier_TXT
    command: "sh /share/import_dates.sh"
```
New in configuration.yaml:
`command_line: !include command_line.yaml`

New in command_line.yaml:
```
- sensor:
     name: "Import Garbage Schedule"
     command: "sh /share/import_dates.sh"
     unique_id: Oud_Papier_TXT
```

### Debug logs

```shell
N/A
```
