### ISSUE TITLE
Lovelace Examples

### ISSUE THREAD

**Issue by rosscullen** [bruxy70/Garbage-Collection#67]
**Is your feature request related to a problem? Please describe.**
Great Component, well done on all the hard work to date!
Would you consider some documentation on Lovelace Examples?

**Describe the solution you'd like**
 A not of novices would get stuck at the part of showing the State (0,1,2) by default, as oppose to the Attributes (next_date, days) output.

**Additional context**
In addition, having some screenshots of Lovelace examples will no doubt attract more users to the component... keep up the good work!

**Comment by bruxy70** [comment]
Good idea. Would you like to suggest how do you do yours?
This is what I do:
```yaml
        - type: 'custom:card-templater'
          card:
            type: picture-entity
            name_template: >-
              {{ states.sensor.smes.attributes.days }} days
            show_name: True
            show_state: False
            entity: sensor.smes
            state_image:
              "0": "/local/kontejnery/smes_dnes.png"
              "1": "/local/kontejnery/smes_zitra.png"
              "2": "/local/kontejnery/smes_off.png"
          entities:
            - sensor.smes
```

There is also a [garbage collection cord by amaximus](https://github.com/amaximus/garbage-collection-card), suppose most people use that?
