### ISSUE TITLE
A specific bin configured in configure.yaml :  icon_color not observed. 

### ISSUE THREAD

**Issue by jinneth** [bruxy70/Garbage-Collection#79]
**Describe the bug**
-Two bins, configured exactly the same, except for "name" in configure.yaml.
-Lovelace custom card respects the "icon_color" syntax for "Green_Bin" but not for "Yellow_Bin"
-Both "Yellow Bin" icons will show as a icon of a red bin with a black up arrow on it.
-The "Green Bin" icon shows as an icon of a green bin with two black stripes indicating the traditional metal round bin style. 
 
**Configuration**
Configure.yaml lines 
```
garbage_collection:
  sensors:
  - name: "Yellow Bin"
    frequency: "even-weeks"
    collection_days: "tue"
    verbose_state: true
  - name: "Green Bin"
    frequency: "odd-weeks"
    collection_days: "tue"
    verbose_state: true

```

Lovelace raw editor, relevant sections:
```
resources:
  - type: module
    url: /local/garbage-collection-card.js
  - badges: []
    cards:
      - entity: sensor.yellow_bin
        hide_before: 4
        icon_color: purple
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - entity: sensor.green_bin
        hide_date: true
        icon_color: green
        icon_size: 35px
        type: 'custom:garbage-collection-card'
      - entity: sensor.yellow_bin
        hide_date: true
        icon_color: yellow
        icon_size: 35px
        type: 'custom:garbage-collection-card'
    path: temporary-page
    title: Temporary Page

```

########################
