### ISSUE TITLE
Card shows up as undefined

### ISSUE THREAD

**Issue by codypet** [bruxy70/Garbage-Collection#85]
**Describe the bug**
The card shows up as undefined and rebooting the pi or restarting Hass doesn't help

**Configuration**
```
garbage_collection:
  sensors:
  - name: "Trash"
    frequency: "weekly"
    collection_days:
    - tue
    exclude_dates:
    - '2019-12-25'
    verbose_state: True
  - name: "Recycling"
    frequency: "weekly"
    icon_normal: mdi:recycle
    collection_days:
    - fri
    exclude_dates:
    - '2019-12-25'
    verbose_state: True
```

**Error log/debug information**
Nothing Unusual
```
2020-01-18 20:47:46 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
**Screenshots**
![image](https://user-images.githubusercontent.com/17790157/72673435-71337a00-3a38-11ea-9d72-4f604037e0d0.png)

**Version**
Home assistant 104.2 
Garbage Collection 2.13
