### ISSUE TITLE
Add last due day to the sensor

### ISSUE THREAD

**Issue by PavelD** [bruxy70/Garbage-Collection#86]
Hi,

We have public containers for plastic, paper and other stuff. For sensors of this kind of waste it will be nice to see when was the last due day as they are almost all the time full.

Only problem with this sensors can be `group`. But for groups will be nice to see the latest due day from all sensors in the group.

Thanks in advance!

**Comment by bruxy70** [comment]
That would not be trivial. How about?

```yaml
binary_sensor:
  - platform: template
    sensors:
      waste:
        entity_id: sensor.waste
        value_template: "{{ is_state('sensor.waste','0') }}"
```

This will be True if the collection is today.
Then you can get the last date by

```yaml
{{ as_timestamp(states.binary_sensor.waste.last_changed) | timestamp_custom ('%Y-%m-%d',true) }}
```
